run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - goimports
    - govet
    - ineffassign
    - gosec
    - misspell
    - stylecheck
    - revive
    - predeclared
    - staticcheck
    - typecheck
    - unused

issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - govet
        - gosec
        - staticcheck
        - unused
